# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(09b22bb3-8da4-418b-a14e-087a777b0654)'
    appType: 'webAppLinux'
    appName: 'flask-ml-service-webapp'  
    deployToSlotOrASE: true
    resourceGroupName: 'azuredevops'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'PYTHON|3.7'
    startUpCommand: 'python app.py'
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
